<div class="modal" id="terms-modal">
  <div class="modal-overlay"></div>
  <div class="modal-body">
    <div class="modal-content">
      <h1>Terms & Conditions</h1>
      <p>THE INFORMATION PROVIDED ON THIS SITE IS NOT INTENDED FOR DISTRIBUTION TO, OR USE BY, ANY PERSON OR ENTITY IN THE UNITED STATES OR THE REPUBLIC OF SINGAPORE, OR IN ANY JURISDICTION OR COUNTRY WHERE SUCH DISTRIBUTION OR USE WOULD BE CONTRARY TO ANY LAW OR REGULATION, OR WHICH WOULD SUBJECT TOKENBOX AND/OR ENTITY CREATING THE TBX TOKENS (INCLUDING THEIR AFFILIATES) OR ANY OF THEIR PRODUCTS OR SERVICES TO ANY REGISTRATION, LICENSING OR OTHER AUTHORIZATION REQUIREMENT WITHIN SUCH JURISDICTION OR COUNTRY.</p>
      <p>YOU ARE ONLY ALLOWED TO PURCHASE TBX TOKENS IF AND BY BUYING TBX TOKENS YOU COVENANT, REPRESENT, AND WARRANT THAT YOU ARE NEITHER A U.S. CITIZEN OR PERMANENT RESIDENT OF THE UNITED STATES, NOR DO YOU HAVE A PRIMARY RESIDENCE OR DOMICILE IN THE UNITED STATES, INCLUDING PUERTO RICO, THE U.S. VIRGIN ISLANDS, AND ANY OTHER POSSESSIONS OF THE UNITED STATES. IN ORDER TO BUY TBX TOKENS AND BY BUYING TBX TOKENS YOU COVENANT, REPRESENT, AND WARRANT THAT NONE OF THE OWNERS OF THE COMPANY, OF WHICH YOU ARE AN AUTHORIZED OFFICER, ARE U.S. CITIZEN OR PERMANENT RESIDENT OF THE UNITED STATES, NOR DO YOU HAVE A PRIMARY RESIDENCE OR DOMICILE IN THE UNITED STATES, INCLUDING PUERTO RICO, THE U.S. VIRGIN ISLANDS, AND ANY OTHER POSSESSIONS OF THE UNITED STATES. SHOULD THIS CHANGE AT ANY TIME, YOU SHALL IMMEDIATELY NOTIFY THE CREATOR OF TBX TOKENS.
      </p>
      <p>
      CREATOR OF TBX TOKENS SHALL RESERVE THE RIGHT TO REFUSE SELLING TBX TOKENS TO ANYONE WHO DOES NOT MEET CRITERIA NECESSARY FOR THEIR BUYING, AS SET OUT HEREUNDER AND BY THE APPLICABLE LAW. IN PARTICULAR, THE CREATOR OF TBX TOKENS MAY REFUSE SELLING TBX TOKENS TO U.S. CITIZENS, PERMANENT RESIDENTS OF THE UNITED STATES AND THOSE USERS WHO DO NOT MEET ELIGIBILITY CRITERIA ESTABLISHED BY THE CREATOR OF TBX TOKENS FROM TO TIME IN ITS SOLE DISCRETION.
      </p>
      <p>
      The data content of this site is intended for general information purposes only and does not constitute solicitation of or an offer to purchase any securities. This site should be used for general research purposes only. It does not, nor does it purport to, constitute any form of professional investment advice, recommendation or independent analysis. Consequently, the information contained on this site has not been prepared in accordance with the relevant rules and regulations governing such publications in various jurisdictions.
      </p>
    </div>
  </div>
</div>
